[package]
name = "life_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.3"
glam = "0.20.1"
macroquad = "0.3.10"
oorandom = "11.1.3"
rstar = "0.9.2"
